require('dotenv').config()

module.exports = async (req, res) => {
    res.setHeader('Cache-Control', 'max-age=0, s-maxage=86400')
    try {
        res.status(200).send([
            {
                name: "IQ",
                precision: 3,
                contract: "everipediaiq",
                icon: "tokens/iq.png",
                marketId: -1,
                side: null,
                allowedTrades: [
                    {token: "YETRUMP", pool: "IQYTRMP"},
                    {token: "NOTRUMP", pool: "IQNTRMP"},
                    {token: "YVAC", pool: "IQYVAC"},
                    {token: "NVAC", pool: "IQNVAC"},
                    {token: "YESDFS", pool: "IQYDFS"},
                    {token: "NODFS", pool: "IQNDFS"},
                    {token: "YEIQUPB", pool: "IQYUPB"},
                    {token: "NOIQUPB", pool: "IQNUPB"},
                    {token: "EOS", pool: "EOSIQ"},
                    {token: "YEBIDEN", pool: "IQYBID"},
                    {token: "NOBIDEN", pool: "IQNBID"},
                ],
                isDefault: true,
                isSelected: false,
            },
            {
                name: "EOS",
                precision: 4,
                contract: "eosio.token",
                icon: "tokens/eos.png",
                marketId: -1,
                side: null,
                allowedTrades: [{token: "IQ", pool: "EOSIQ"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "YETRUMP",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/yestrump.png",
                marketId: 69,
                side: 1,
                allowedTrades: [{token: "IQ", pool: "IQYTRMP"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "NOTRUMP",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/notrump.png",
                marketId: 69,
                side: 0,
                allowedTrades: [{token: "IQ", pool: "IQNTRMP"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "YVAC",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/yvac.png",
                marketId: 117,
                side: 1,
                allowedTrades: [{token: "IQ", pool: "IQYVAC"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "NVAC",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/nvac.png",
                marketId: 117,
                side: 0,
                allowedTrades: [{token: "IQ", pool: "IQNVAC"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "YESDFS",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/yesdfs.png",
                marketId: 220,
                side: 1,
                allowedTrades: [{token: "IQ", pool: "IQYDFS"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "NODFS",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/nodfs.png",
                marketId: 220,
                side: 0,
                allowedTrades: [{token: "IQ", pool: "IQNDFS"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "YEIQUPB",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/yeskrw.png",
                marketId: 216,
                side: 1,
                allowedTrades: [{token: "IQ", pool: "IQYUPB"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "NOIQUPB",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/nokrw.png",
                marketId: 216,
                side: 0,
                allowedTrades: [{token: "IQ", pool: "IQNUPB"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "YEBIDEN",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/yebiden.png",
                marketId: 206,
                side: 1,
                allowedTrades: [{token: "IQ", pool: "IQYBID"}],
                isSelected: false,
                isDefault: false,
            },
            {
                name: "NOBIDEN",
                precision: 3,
                contract: "prediqtokens",
                icon: "tokens/nobiden.png",
                marketId: 206,
                side: 0,
                allowedTrades: [{token: "IQ", pool: "IQNBID"}],
                isSelected: false,
                isDefault: false,
            },
        ]);
    } catch (e) {
        console.log('\nCaught exception: ' + e)
        res.status(500).send('ERROR 500');
    }
}
